---
# tasks file for alertmanager-discord

- name: Pull docker file
  docker_image:
    name: funkypenguin/alertmanager-discord
    source: pull

- name: Create alermanager-discord container.
  docker_container:
    recreate: true
    name: "alertmanager-discord"
    hostname: "alertmanager-discord"
    image: "funkypenguin/alertmanager-discord"
    ports:
      - "{{ alertmanager_discord_port }}:9094"
    env:
      DISCORD_WEBHOOK: '{{ discord_webhook }}'
  tags: molecule-notest
  changed_when: false
  become: yes