---
# tasks file for alertmanager-discord

- name: Pull docker file
  docker_image:
    name: funkypenguin/alertmanager-discord
    source: pull

- name: Create alermanager-discord container.
  docker_container:
    recreate: true
    name: "alertmanager-discord"
    hostname: "alertmanager-discord"
    image: "alertmanager-discord"
    ports:
      - "{{ alertmanager_discord_port }}:{{ alertmanager_discord_port }}"
  tags: molecule-notest
  changed_when: false
  become: yes